AWSTemplateFormatVersion: '2010-09-09'
Description: >
  This template contains the security groups for mediawiki installation.

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  VpcId:
    Type: String
    Description: Choose which VPC the security groups should be deployed to

Resources:  
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: !Sub "SG For ${EnvironmentName}"
      SecurityGroupEgress: 
        - CidrIp: 0.0.0.0/0
          IpProtocol: "-1"
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} 

      
Outputs:
  SecurityGroupId:
    Description: A reference to the security group
    Value: !Ref SecurityGroup